db:
  build: ./db
  ports:
    - "3307:3306"

api:
 build: ./api
 ports:
  - "8080:8080"
 volumes:
  - ./api:/api
 command: /bin/sh /api/start.sh
 links:
  - db

client:
 build: ./client
 ports:
  - "44200:4200"
 volumes:
  - ./client:/client
 links:
  - api